# Generated by Django 5.2.11 on 2026-02-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_title', models.CharField(default='Informativa sulla tutela dei dati personali', max_length=200, verbose_name='Privacy Policy Title')),
                ('data_controller', models.TextField(help_text='Company name, address, and contact information', verbose_name='Data Controller (Titolare del Trattamento)')),
                ('legal_basis', models.TextField(help_text='GDPR legal basis information', verbose_name='Legal Basis (Base Giuridica)')),
                ('data_purposes', models.TextField(help_text='List of purposes, one per line', verbose_name='Data Collection Purposes (Finalità della Raccolta Dati)')),
                ('data_sharing', models.TextField(verbose_name='Data Sharing (Condivisione dei Dati)')),
                ('data_storage', models.TextField(verbose_name='Data Storage (Conservazione dei Dati)')),
                ('retention_period', models.TextField(verbose_name='Retention Period (Periodo di Conservazione)')),
                ('user_rights', models.TextField(verbose_name="User Rights (Diritti dell'Utente)")),
                ('cookie_title', models.CharField(default='Cookie Policy', max_length=200, verbose_name='Cookie Policy Title')),
                ('cookie_types', models.TextField(help_text='List cookie types with descriptions', verbose_name='Cookie Types (Tipologie Utilizzate)')),
                ('consent_requirements', models.TextField(verbose_name='Consent Requirements (Requisiti di Consenso)')),
                ('cookies_listed', models.TextField(help_text='List specific cookies used', verbose_name='Cookies Listed')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
            },
        ),
    ]
