# Generated by Django 5.2.11 on 2026-02-05 05:37

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='consent_requirements',
            field=models.JSONField(default=pages.models.empty_translations, verbose_name='Consent Requirements (IT / EN / DE)'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='cookie_title',
            field=models.JSONField(default=pages.models.empty_translations, help_text='{"it": "...", "en": "...", "de": "..."}', verbose_name='Cookie Policy Title (IT / EN / DE)'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='cookie_types',
            field=models.JSONField(default=pages.models.empty_translations, help_text='List cookie types with descriptions', verbose_name='Cookie Types (IT / EN / DE)'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='cookies_listed',
            field=models.JSONField(default=pages.models.empty_translations, help_text='List specific cookies used', verbose_name='Cookies Listed (IT / EN / DE)'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='data_controller',
            field=models.JSONField(default=pages.models.empty_translations, help_text='Company name, address, and contact information', verbose_name='Data Controller (IT / EN / DE)'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='data_purposes',
            field=models.JSONField(default=pages.models.empty_translations, help_text='List of purposes, one per line', verbose_name='Data Collection Purposes (IT / EN / DE)'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='data_sharing',
            field=models.JSONField(default=pages.models.empty_translations, verbose_name='Data Sharing (IT / EN / DE)'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='data_storage',
            field=models.JSONField(default=pages.models.empty_translations, verbose_name='Data Storage (IT / EN / DE)'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='legal_basis',
            field=models.JSONField(default=pages.models.empty_translations, help_text='GDPR legal basis information', verbose_name='Legal Basis (IT / EN / DE)'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='privacy_title',
            field=models.JSONField(default=pages.models.empty_translations, help_text='{"it": "...", "en": "...", "de": "..."}', verbose_name='Privacy Policy Title (IT / EN / DE)'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='retention_period',
            field=models.JSONField(default=pages.models.empty_translations, verbose_name='Retention Period (IT / EN / DE)'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='user_rights',
            field=models.JSONField(default=pages.models.empty_translations, verbose_name='User Rights (IT / EN / DE)'),
        ),
    ]
