# Generated by Django 4.2.16 on 2026-02-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('privacy_accepted', models.BooleanField(default=False)),
                ('updates_accepted', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('contact', 'Contact Page'), ('property', 'Property Detail'), ('vendi', 'Sell Page')], default='contact', max_length=20)),
                ('property_ref', models.CharField(blank=True, help_text='Property reference if from detail page', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
