# Generated by Django 4.2.16 on 2026-02-05 01:20

from django.db import migrations, models
import django.db.models.deletion
import properties.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(default=properties.models.empty_translations, help_text='{"it": "...", "en": "...", "de": "..."}')),
                ('description', models.JSONField(blank=True, default=properties.models.empty_translations, help_text='{"it": "...", "en": "...", "de": "..."}')),
                ('composition', models.JSONField(blank=True, default=properties.models.empty_translations_list, help_text='{"it": [...], "en": [...], "de": [...]}')),
                ('composition_note', models.JSONField(blank=True, default=properties.models.empty_translations, help_text='{"it": "...", "en": "...", "de": "..."}')),
                ('location_note', models.JSONField(blank=True, default=properties.models.empty_translations, help_text='{"it": "...", "en": "...", "de": "..."}')),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ref', models.CharField(max_length=50, unique=True)),
                ('area', models.DecimalField(decimal_places=2, help_text='Total area in m²', max_digits=10)),
                ('commercial_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('total_rooms', models.IntegerField(blank=True, null=True)),
                ('energy_class', models.CharField(blank=True, max_length=10)),
                ('condominium_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('main_image', models.ImageField(upload_to='properties/main/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/')),
                ('order', models.IntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='properties.property')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
