# Generated by Django 4.2.16 on 2026-02-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('appartamento', 'Apartment'), ('attico', 'Penthouse'), ('garage', 'Garage'), ('casa-singola', 'Detached house'), ('rustico', 'Farmhouse'), ('terreno', 'Building land'), ('villa', 'Villa'), ('villa-bifamiliare', 'Semi-detached villa'), ('villa-schiera', 'Terraced villa')], max_length=50),
        ),
    ]
